wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25AZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25BZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25BZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25EZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25EZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25FZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25CN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25DN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25DN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25GN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25GN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25HN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25HN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25DZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25DZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25GZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25GZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25HZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_25HZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_26CZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_26CZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31AN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31BN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31BN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31EN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31EN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31FN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31FN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31AZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31AZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31BZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31BZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31EZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31EZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31FZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31FZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_32AZ1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_32AZ2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31DN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31DN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31GN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31GN2.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_31HN1.zip
wget https://ns_hwh.fundaments.nl/hwh-ahn/AHN3/DTM_50cm/M_32CN1.zip
