# THIS DATA DOES NOT SEEM TO BE ALIVE ANYMORE

wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25az2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25bz1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25bz2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25ez1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25ez2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25fz1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25cn2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25dn1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25dn2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25gn1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25gn2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25hn1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25hn2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25dz1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25dz2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25gz1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25gz2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25hz1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n25hz2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31an2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31bn1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31bn2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31en1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31en2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31fn1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31fn2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31az1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31az2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31bz1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31bz2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31ez1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31ez2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31fz1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31fz2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n32az1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n32az2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31dn1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31dn2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31gn1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31gn2.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n31hn1.zip
wget http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_non/n32cn1.zip
